In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('./MAHACROPS (1).csv')
df.head()

Unnamed: 0   State_Name District_Name  Crop_Year       Season       Crop  \
0      125191  Maharashtra    AHMEDNAGAR       1997  Autumn           Maize   
1      125192  Maharashtra    AHMEDNAGAR       1997  Kharif       Arhar/Tur   
2      125193  Maharashtra    AHMEDNAGAR       1997  Kharif           Bajra   
3      125194  Maharashtra    AHMEDNAGAR       1997  Kharif            Gram   
4      125195  Maharashtra    AHMEDNAGAR       1997  Kharif           Jowar   

       Area  Production  
0       1.0      1113.0  
1   17600.0      6300.0  
2  274100.0    152800.0  
3   40800.0     18600.0  
4     900.0      1100.0

In [3]:
df.drop(['Unnamed: 0','State_Name','Crop_Year'],axis=1,inplace=True)
df.head()

District_Name       Season       Crop      Area  Production
0    AHMEDNAGAR  Autumn           Maize       1.0      1113.0
1    AHMEDNAGAR  Kharif       Arhar/Tur   17600.0      6300.0
2    AHMEDNAGAR  Kharif           Bajra  274100.0    152800.0
3    AHMEDNAGAR  Kharif            Gram   40800.0     18600.0
4    AHMEDNAGAR  Kharif           Jowar     900.0      1100.0

In [4]:
df['Crop'].nunique()

34

In [5]:
df.isnull().sum()

District_Name      0
Season             0
Crop               0
Area               0
Production       132
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.isnull().sum()

District_Name    0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [8]:
df.shape

(12496, 5)

In [9]:
df1=pd.get_dummies(data=df)

In [10]:
df1.head()

Area  Production  District_Name_AHMEDNAGAR  District_Name_AKOLA  \
0       1.0      1113.0                         1                    0   
1   17600.0      6300.0                         1                    0   
2  274100.0    152800.0                         1                    0   
3   40800.0     18600.0                         1                    0   
4     900.0      1100.0                         1                    0   

   District_Name_AMRAVATI  District_Name_AURANGABAD  District_Name_BEED  \
0                       0                         0                   0   
1                       0                         0                   0   
2                       0                         0                   0   
3                       0                         0                   0   
4                       0                         0                   0   

   District_Name_BHANDARA  District_Name_BULDHANA  District_Name_CHANDRAPUR  \
0                       0                       0                         0   
1                       0                       0                         0   
2                       0                       0                         0   
3                       0                       0                         0   
4                       0                       0                         0   

   ...  Crop_Small millets  Crop_Soyabean  Crop_Sugarcane  Crop_Sunflower  \
0  ...                   0              0               0               0   
1  ...                   0              0               0               0   
2  ...                   0              0               0               0   
3  ...                   0              0               0               0   
4  ...                   0              0               0               0   

   Crop_Tobacco  Crop_Tomato  Crop_Total foodgrain  Crop_Urad  Crop_Wheat  \
0             0            0                     0          0           0   
1             0            0                     0          0           0   
2             0            0                     0          0           0   
3             0            0                     0          0           0   
4             0            0                     0          0           0   

   Crop_other oilseeds  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  

[5 rows x 76 columns]

In [11]:
df1.columns

Index(['Area', 'Production', 'District_Name_AHMEDNAGAR', 'District_Name_AKOLA',
       'District_Name_AMRAVATI', 'District_Name_AURANGABAD',
       'District_Name_BEED', 'District_Name_BHANDARA',
       'District_Name_BULDHANA', 'District_Name_CHANDRAPUR',
       'District_Name_DHULE', 'District_Name_GADCHIROLI',
       'District_Name_GONDIA', 'District_Name_HINGOLI',
       'District_Name_JALGAON', 'District_Name_JALNA',
       'District_Name_KOLHAPUR', 'District_Name_LATUR', 'District_Name_MUMBAI',
       'District_Name_NAGPUR', 'District_Name_NANDED',
       'District_Name_NANDURBAR', 'District_Name_NASHIK',
       'District_Name_OSMANABAD', 'District_Name_PALGHAR',
       'District_Name_PARBHANI', 'District_Name_PUNE', 'District_Name_RAIGAD',
       'District_Name_RATNAGIRI', 'District_Name_SANGLI',
       'District_Name_SATARA', 'District_Name_SINDHUDURG',
       'District_Name_SOLAPUR', 'District_Name_THANE', 'District_Name_WARDHA',
       'District_Name_WASHIM', 'District_Name_Y

In [12]:
df1.shape

(12496, 76)

In [13]:
X = df1.drop('Production',axis=1)
y = df1['Production']

In [14]:
y.head()

0      1113.0
1      6300.0
2    152800.0
3     18600.0
4      1100.0
Name: Production, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [16]:
X_train.columns

Index(['Area', 'District_Name_AHMEDNAGAR', 'District_Name_AKOLA',
       'District_Name_AMRAVATI', 'District_Name_AURANGABAD',
       'District_Name_BEED', 'District_Name_BHANDARA',
       'District_Name_BULDHANA', 'District_Name_CHANDRAPUR',
       'District_Name_DHULE', 'District_Name_GADCHIROLI',
       'District_Name_GONDIA', 'District_Name_HINGOLI',
       'District_Name_JALGAON', 'District_Name_JALNA',
       'District_Name_KOLHAPUR', 'District_Name_LATUR', 'District_Name_MUMBAI',
       'District_Name_NAGPUR', 'District_Name_NANDED',
       'District_Name_NANDURBAR', 'District_Name_NASHIK',
       'District_Name_OSMANABAD', 'District_Name_PALGHAR',
       'District_Name_PARBHANI', 'District_Name_PUNE', 'District_Name_RAIGAD',
       'District_Name_RATNAGIRI', 'District_Name_SANGLI',
       'District_Name_SATARA', 'District_Name_SINDHUDURG',
       'District_Name_SOLAPUR', 'District_Name_THANE', 'District_Name_WARDHA',
       'District_Name_WASHIM', 'District_Name_YAVATMAL', 'Sea

In [17]:
from sklearn.linear_model import LinearRegression
crop_model = LinearRegression()
crop_model.fit(X_train,y_train)

LinearRegression()

In [18]:
crop_predictions = crop_model.predict(X_test)
crop_predictions

array([  -6480.2776669 ,  157850.84428646,  186566.11983065, ...,
        -28806.85799988, -245082.72055071,  -19937.8511679 ])

In [19]:
crop_predictions = crop_model.predict(X_test)
crop_predictions

array([  -6480.2776669 ,  157850.84428646,  186566.11983065, ...,
        -28806.85799988, -245082.72055071,  -19937.8511679 ])

In [20]:
acc=crop_model.score(X_test,y_test)

In [21]:
acc

0.3082088306296139

In [22]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(X_train,y_train)

RandomForestRegressor()

In [23]:
rf.predict(X_test)

array([ 7399.91666667, 13307.        , 28167.        , ...,
         112.33333333,   445.61777778,  4911.        ])

In [24]:
rf.score(X_test,y_test)

0.9651295091205567

In [25]:
def mah(Area,dist_name,season,crop):
  mah_dict={
      'Area':0,
      'District_Name_AHMEDNAGAR':0,
      'District_Name_AKOLA':0,
      'District_Name_AMRAVATI':0,
      'District_Name_AURANGABAD':0,
      'District_Name_BEED':0, 
      'District_Name_BHANDARA':0,
      'District_Name_BULDHANA':0, 
      'District_Name_CHANDRAPUR':0,
      'District_Name_DHULE':0, 
      'District_Name_GADCHIROLI':0,
      'District_Name_GONDIA':0, 
      'District_Name_HINGOLI':0,
      'District_Name_JALGAON':0, 
      'District_Name_JALNA':0,
      'District_Name_KOLHAPUR':0, 
      'District_Name_LATUR':0, 
      'District_Name_MUMBAI':0,
      'District_Name_NAGPUR':0, 
      'District_Name_NANDED':0,
      'District_Name_NANDURBAR':0, 
      'District_Name_NASHIK':0,
      'District_Name_OSMANABAD':0, 
      'District_Name_PALGHAR':0,
      'District_Name_PARBHANI':0, 
      'District_Name_PUNE':0, 
      'District_Name_RAIGAD':0,
      'District_Name_RATNAGIRI':0, 
      'District_Name_SANGLI':0,
      'District_Name_SATARA':0, 
      'District_Name_SINDHUDURG':0,
      'District_Name_SOLAPUR':0, 
      'District_Name_THANE':0, 
      'District_Name_WARDHA':0,
      'District_Name_WASHIM':0, 
      'District_Name_YAVATMAL':0, 
      'Season_Autumn     ':0,
      'Season_Kharif     ':0, 
      'Season_Rabi       ':0, 
      'Season_Summer     ':0,
      'Season_Whole Year ':0, 
      'Crop_Arhar/Tur':0, 
      'Crop_Bajra':0, 
      'Crop_Banana':0,
      'Crop_Castor seed':0, 
      'Crop_Cotton(lint)':0, 
      'Crop_Gram':0, 
      'Crop_Grapes':0,
      'Crop_Groundnut':0, 
      'Crop_Jowar':0, 
      'Crop_Linseed':0, 
      'Crop_Maize':0,
      'Crop_Mango':0, 
      'Crop_Moong(Green Gram)':0, 
      'Crop_Niger seed':0, 
      'Crop_Onion':0,
      'Crop_Other  Rabi pulses':0, 
      'Crop_Other Cereals & Millets':0,
      'Crop_Other Kharif pulses':0, 
      'Crop_Pulses total':0, 
      'Crop_Ragi':0,
      'Crop_Rapeseed &Mustard':0, 
      'Crop_Rice':0, 
      'Crop_Safflower':0, 
      'Crop_Sesamum':0,
      'Crop_Small millets':0, 
      'Crop_Soyabean':0, 
      'Crop_Sugarcane':0,
      'Crop_Sunflower':0, 
      'Crop_Tobacco':0, 
      'Crop_Tomato':0, 
      'Crop_Total foodgrain':0,
      'Crop_Urad':0, 
      'Crop_Wheat':0, 
      'Crop_other oilseeds':0
  }
  mah_dict['Area'] = Area
  mah_dict[dist_name] = 1
  mah_dict[season] = 1
  mah_dict[crop] = 1
  data=list(mah_dict.values())
  print(mah_dict)
  input_arr=np.array(data)
  return input_arr

In [26]:
arr=mah(31500,'District_Name_NANDED','Season_Rabi       ','Crop_Wheat')
print(len(arr))
print(rf.predict([arr]))

{'Area': 31500, 'District_Name_AHMEDNAGAR': 0, 'District_Name_AKOLA': 0, 'District_Name_AMRAVATI': 0, 'District_Name_AURANGABAD': 0, 'District_Name_BEED': 0, 'District_Name_BHANDARA': 0, 'District_Name_BULDHANA': 0, 'District_Name_CHANDRAPUR': 0, 'District_Name_DHULE': 0, 'District_Name_GADCHIROLI': 0, 'District_Name_GONDIA': 0, 'District_Name_HINGOLI': 0, 'District_Name_JALGAON': 0, 'District_Name_JALNA': 0, 'District_Name_KOLHAPUR': 0, 'District_Name_LATUR': 0, 'District_Name_MUMBAI': 0, 'District_Name_NAGPUR': 0, 'District_Name_NANDED': 1, 'District_Name_NANDURBAR': 0, 'District_Name_NASHIK': 0, 'District_Name_OSMANABAD': 0, 'District_Name_PALGHAR': 0, 'District_Name_PARBHANI': 0, 'District_Name_PUNE': 0, 'District_Name_RAIGAD': 0, 'District_Name_RATNAGIRI': 0, 'District_Name_SANGLI': 0, 'District_Name_SATARA': 0, 'District_Name_SINDHUDURG': 0, 'District_Name_SOLAPUR': 0, 'District_Name_THANE': 0, 'District_Name_WARDHA': 0, 'District_Name_WASHIM': 0, 'District_Name_YAVATMAL': 0, 'Se

c:\Users\salman\OneDrive\Desktop\Bytecamp-hackethon\env\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


In [27]:
rf.predict([arr])

c:\Users\salman\OneDrive\Desktop\Bytecamp-hackethon\env\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([41895.66666667])

In [28]:
import pickle
filename='model.pkl'
pickle.dump(rf,open(filename,'wb'))

In [29]:
with open(filename, 'rb') as f:
    classification_dict = pickle.load(f)

In [31]:
classification_dict.predict([arr])

c:\Users\salman\OneDrive\Desktop\Bytecamp-hackethon\env\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([41895.66666667])

In [32]:
arr

array([31500,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     1,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     1,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     1,     0])